# I didn't noticed that you have updated the exercise documentation in the google drive and I misunderstood what you expect for the bonus questions. Therefore I make this revised exercise.

## Question 1

In [1]:
from pandas_datareader import data as pdr
import pandas as pd

import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)

dict = {'Tencent':'0700.HK',
        'Alibaba':'9988.HK',
        'Meituan':'3690.HK',
        'HSBC':'0005.HK',
        'CCB':'0939.HK',
        'HKEX':'0388.HK',
        }

dfs = []
for i,j in dict.items():
        s=pdr.get_data_yahoo(j, interval='1mo', start="2021-12-01", end="2023-07-30")['Adj Close']
        df = pd.DataFrame({'Date': s.index, 'Adj_Close': s.values, 'Ticker': i})
        df['Year'] = s.index.year
        df['Month'] = s.index.month
        df['Stock_Symbol'] = j
        df['Monthly_Return'] = df['Adj_Close'].pct_change()
        df.dropna(inplace=True)
        dfs.append(df)
raw_data = pd.concat(dfs, ignore_index=True)
data = raw_data.groupby('Ticker')
for key, group in data:
    print("Group:", key)
    print(group)
    print()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Group: Alibaba
         Date   Adj_Close   Ticker  Year  Month Stock_Symbol  Monthly_Return
19 2022-01-01  114.699997  Alibaba  2022      1      9988.HK       -0.035324
20 2022-02-01  104.199997  Alibaba  2022      2      9988.HK       -0.091543
21 2022-03-01  112.099998  Alibaba  2022      3      9988.HK        0.075816
22 2022-04-01  102.099998  Alibaba  2022      4      9988.HK       -0.089206
23 2022-05-01   96.250000  Alibaba  2022      5      9988.HK       -0.057297
24 2022-06-01  111.900002  Alibaba  2022      6      9988.HK        0.162597
25 2022-07-01   93.099998  Alibaba  2022      7      9988.HK       -0.168007
26 2022-08-01   94.300003  Alibaba  2022      8      9988.HK        0.012889
27 2022-09-01   77.949997  Alibaba  2022      9      9988.HK       -0.173383
28 2022-10-01   61.450001  Alibaba  2022     10      9988.HK       -0.211674
29 2022-11-01   79.900002  Alibaba  2022     11      9988.HK        0.300244
30 2022-12-01   86.250000  Alibaba  2022     12      9988.HK        0.079474
31 2023-01-01  107.599998  Alibaba  2023      1      9988.HK        0.247536
32 2023-02-01   86.500000  Alibaba  2023      2      9988.HK       -0.196097
33 2023-03-01  100.400002  Alibaba  2023      3      9988.HK        0.160694
34 2023-04-01   82.050003  Alibaba  2023      4      9988.HK       -0.182769
35 2023-05-01   77.900002  Alibaba  2023      5      9988.HK       -0.050579
36 2023-06-01   81.199997  Alibaba  2023      6      9988.HK        0.042362
37 2023-07-01   97.500000  Alibaba  2023      7      9988.HK        0.200739

Group: CCB
         Date  Adj_Close Ticker  Year  Month Stock_Symbol  Monthly_Return
76 2022-01-01   5.065426    CCB  2022      1      0939.HK        0.107407
77 2022-02-01   4.963778    CCB  2022      2      0939.HK       -0.020067
78 2022-03-01   4.989191    CCB  2022      3      0939.HK        0.005120
79 2022-04-01   4.735072    CCB  2022      4      0939.HK       -0.050934
80 2022-05-01   4.946837    CCB  2022      5      0939.HK        0.044723
81 2022-06-01   4.464013    CCB  2022      6      0939.HK       -0.097603
82 2022-07-01   4.587169    CCB  2022      7      0939.HK        0.027589
83 2022-08-01   4.458985    CCB  2022      8      0939.HK       -0.027944
84 2022-09-01   4.156836    CCB  2022      9      0939.HK       -0.067762
85 2022-10-01   3.818063    CCB  2022     10      0939.HK       -0.081498
86 2022-11-01   4.312489    CCB  2022     11      0939.HK        0.129496
87 2022-12-01   4.477297    CCB  2022     12      0939.HK        0.038217
88 2023-01-01   4.651261    CCB  2023      1      0939.HK        0.038855
89 2023-02-01   4.394893    CCB  2023      2      0939.HK       -0.055118
90 2023-03-01   4.660418    CCB  2023      3      0939.HK        0.060417
91 2023-04-01   4.806914    CCB  2023      4      0939.HK        0.031434
92 2023-05-01   4.587169    CCB  2023      5      0939.HK       -0.045714
93 2023-06-01   4.642106    CCB  2023      6      0939.HK        0.011976
94 2023-07-01   4.147680    CCB  2023      7      0939.HK       -0.106509

Group: HKEX
          Date   Adj_Close Ticker  Year  Month Stock_Symbol  Monthly_Return
95  2022-01-01  425.226990   HKEX  2022      1      0388.HK       -0.033816
96  2022-02-01  364.922089   HKEX  2022      2      0388.HK       -0.141818
97  2022-03-01  358.930237   HKEX  2022      3      0388.HK       -0.016420
98  2022-04-01  330.516998   HKEX  2022      4      0388.HK       -0.079161
99  2022-05-01  331.886841   HKEX  2022      5      0388.HK        0.004145
100 2022-06-01  377.677826   HKEX  2022      6      0388.HK        0.137972
101 2022-07-01  351.259918   HKEX  2022      7      0388.HK       -0.069948
102 2022-08-01  310.948181   HKEX  2022      8      0388.HK       -0.114763
103 2022-09-01  266.651520   HKEX  2022      9      0388.HK       -0.142457
104 2022-10-01  206.714264   HKEX  2022     10      0388.HK       -0.224777
105 2022-11-01  302.653412   HKEX  2022     11      0388.HK        0.464115
106 2022-12-01  333.512207   HKEX  2022     12      0388.HK        0.101961
107 2023-01-01  348.545959   HKEX  2023      1      0388.HK        0.045077
108 2023-02-01  311.159363   HKEX  2023      2      0388.HK       -0.107264
109 2023-03-01  344.391907   HKEX  2023      3      0388.HK        0.106802
110 2023-04-01  324.000000   HKEX  2023      4      0388.HK       -0.059211
111 2023-05-01  286.600006   HKEX  2023      5      0388.HK       -0.115432
112 2023-06-01  295.200012   HKEX  2023      6      0388.HK        0.030007
113 2023-07-01  325.799988   HKEX  2023      7      0388.HK        0.103658

Group: HSBC
         Date  Adj_Close Ticker  Year  Month Stock_Symbol  Monthly_Return
57 2022-01-01  51.045486   HSBC  2022      1      0005.HK        0.174840
58 2022-02-01  50.119072   HSBC  2022      2      0005.HK       -0.018149
59 2022-03-01  50.211716   HSBC  2022      3      0005.HK        0.001848
60 2022-04-01  46.304775   HSBC  2022      4      0005.HK       -0.077809
61 2022-05-01  49.690605   HSBC  2022      5      0005.HK        0.073121
62 2022-06-01  49.261417   HSBC  2022      6      0005.HK       -0.008637
63 2022-07-01  47.115471   HSBC  2022      7      0005.HK       -0.043562
64 2022-08-01  46.352467   HSBC  2022      8      0005.HK       -0.016194
65 2022-09-01  39.884640   HSBC  2022      9      0005.HK       -0.139536
66 2022-10-01  38.917740   HSBC  2022     10      0005.HK       -0.024242
67 2022-11-01  45.686039   HSBC  2022     11      0005.HK        0.173913
68 2022-12-01  46.943008   HSBC  2022     12      0005.HK        0.027513
69 2023-01-01  56.031876   HSBC  2023      1      0005.HK        0.193615
70 2023-02-01  57.337189   HSBC  2023      2      0005.HK        0.023296
71 2023-03-01  51.439098   HSBC  2023      3      0005.HK       -0.102867
72 2023-04-01  55.967602   HSBC  2023      4      0005.HK        0.088036
73 2023-05-01  57.512569   HSBC  2023      5      0005.HK        0.027605
74 2023-06-01  60.904465   HSBC  2023      6      0005.HK        0.058977
75 2023-07-01  65.097885   HSBC  2023      7      0005.HK        0.068852

Group: Meituan
         Date   Adj_Close   Ticker  Year  Month Stock_Symbol  Monthly_Return
38 2022-01-01  220.199997  Meituan  2022      1      3690.HK       -0.023070
39 2022-02-01  172.199997  Meituan  2022      2      3690.HK       -0.217984
40 2022-03-01  155.600006  Meituan  2022      3      3690.HK       -0.096399
41 2022-04-01  172.000000  Meituan  2022      4      3690.HK        0.105398
42 2022-05-01  187.000000  Meituan  2022      5      3690.HK        0.087209
43 2022-06-01  194.199997  Meituan  2022      6      3690.HK        0.038503
44 2022-07-01  176.300003  Meituan  2022      7      3690.HK       -0.092173
45 2022-08-01  189.800003  Meituan  2022      8      3690.HK        0.076574
46 2022-09-01  165.600006  Meituan  2022      9      3690.HK       -0.127503
47 2022-10-01  124.800003  Meituan  2022     10      3690.HK       -0.246377
48 2022-11-01  163.600006  Meituan  2022     11      3690.HK        0.310897
49 2022-12-01  174.699997  Meituan  2022     12      3690.HK        0.067848
50 2023-01-01  174.600006  Meituan  2023      1      3690.HK       -0.000572
51 2023-02-01  136.100006  Meituan  2023      2      3690.HK       -0.220504
52 2023-03-01  143.500000  Meituan  2023      3      3690.HK        0.054372
53 2023-04-01  133.000000  Meituan  2023      4      3690.HK       -0.073171
54 2023-05-01  110.199997  Meituan  2023      5      3690.HK       -0.171429
55 2023-06-01  122.300003  Meituan  2023      6      3690.HK        0.109800
56 2023-07-01  146.300003  Meituan  2023      7      3690.HK        0.196239

Group: Tencent
         Date   Adj_Close   Ticker  Year  Month Stock_Symbol  Monthly_Return
0  2022-01-01  465.681793  Tencent  2022      1      0700.HK        0.031524
1  2022-02-01  416.267334  Tencent  2022      2      0700.HK       -0.106112
2  2022-03-01  369.817749  Tencent  2022      3      0700.HK       -0.111586
3  2022-04-01  372.980255  Tencent  2022      4      0700.HK        0.008552
4  2022-05-01  358.155914  Tencent  2022      5      0700.HK       -0.039746
5  2022-06-01  351.896881  Tencent  2022      6      0700.HK       -0.017476
6  2022-07-01  304.633057  Tencent  2022      7      0700.HK       -0.134312
7  2022-08-01  324.889008  Tencent  2022      8      0700.HK        0.066493
8  2022-09-01  264.518433  Tencent  2022      9      0700.HK       -0.185819
9  2022-10-01  204.147858  Tencent  2022     10      0700.HK       -0.228228
10 2022-11-01  285.171539  Tencent  2022     11      0700.HK        0.396887
11 2022-12-01  314.985474  Tencent  2022     12      0700.HK        0.104547
12 2023-01-01  379.500549  Tencent  2023      1      0700.HK        0.204819
13 2023-02-01  341.173157  Tencent  2023      2      0700.HK       -0.100994
14 2023-03-01  383.075104  Tencent  2023      3      0700.HK        0.122817
15 2023-04-01  341.967499  Tencent  2023      4      0700.HK       -0.107310
16 2023-05-01  308.406250  Tencent  2023      5      0700.HK       -0.098142
17 2023-06-01  331.600006  Tencent  2023      6      0700.HK        0.075205
18 2023-07-01  354.399994  Tencent  2023      7      0700.HK        0.068758

## Question 2

In [2]:
raw_data_1 = pd.read_csv('data_exercises_week3.csv').sort_values(by=['Year','Month','Stock_Symbol'], ascending=True)
raw_data_1['Monthly_Return']=raw_data_1.groupby('Stock_Symbol')['Adj Close'].pct_change()
sorted = raw_data_1.dropna().sort_values(['Year','Month','Monthly_Return'], ascending=False).groupby(['Year','Month']).first()
sorted.reset_index(inplace=True)
sorted

    Year  Month Stock_Symbol  Adj Close  Monthly_Return
0   2022      2      0005.HK     50.198       -0.018151
1   2022      3      9988.HK    112.100        0.075816
2   2022      4      3690.HK    172.000        0.105398
3   2022      5      3690.HK    187.000        0.087209
4   2022      6      9988.HK    111.900        0.162597
5   2022      7      0939.HK      4.587        0.027554
6   2022      8      3690.HK    189.800        0.076574
7   2022      9      0939.HK      4.157       -0.067728
8   2022     10      0005.HK     38.979       -0.024232
9   2022     11      0388.HK    302.653        0.464115
10  2022     12      0700.HK    314.985        0.104544
11  2023      1      9988.HK    107.600        0.247536
12  2023      2      0005.HK     57.427        0.023289
13  2023      3      9988.HK    100.400        0.160694
14  2023      4      0005.HK     56.055        0.088024
15  2023      5      0005.HK     57.603        0.027616
16  2023      6      3690.HK    122.300        0.109800
17  2023      7      9988.HK     97.500        0.200739

## Question 3

In [3]:
output = sorted[['Year', 'Month', 'Stock_Symbol', 'Monthly_Return']]
output.to_csv('stock_highret.csv',index=False)